server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: bank
    password: bank
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    validateOnMigrate: false
jwt:
  secret: "change-me-super-secret"
  issuer: "bank-auth"
